/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const AgeTrait: typeof import('./src/composition/AgeTrait')['AgeTrait']
  const GameEngine: typeof import('./src/GameEngine')['GameEngine']
  const PositionTrait: typeof import('./src/composition/PositionTrait')['PositionTrait']
  const SizeTrait: typeof import('./src/composition/SizeTrait')['SizeTrait']
  const StateTrait: typeof import('./src/composition/StateTrait')['StateTrait']
}
