/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Age: typeof import('./src/composition/Age')['Age']
  const GameEngine: typeof import('./src/GameEngine')['GameEngine']
  const Position: typeof import('./src/composition/Position')['Position']
  const Size: typeof import('./src/composition/Size')['Size']
  const State: typeof import('./src/composition/State')['State']
}
