/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const AgeTrait: typeof import('./composition/AgeTrait')['AgeTrait']
  const GameEngine: typeof import('./GameEngine')['GameEngine']
  const PositionTrait: typeof import('./composition/PositionTrait')['PositionTrait']
  const SizeTrait: typeof import('./composition/SizeTrait')['SizeTrait']
  const StateTrait: typeof import('./composition/StateTrait')['StateTrait']
}
